### ISSUE TITLE
Error using docker image on Gitlab

### ISSUE THREAD

**Issue by vincent-paing** [stoplightio/spectral#1186]
**Describe the bug**
When running with the docker image on Gitlab, it throws an error saying 
```
Unknown arguments: c, sh
```

**To Reproduce**

I have the config set up as follows:
```yml
stages:
  - lint

lint:
  stage: lint
  image: stoplight/spectral
  script:
    - spectral lint ./*.yaml
```

**Expected behavior**
it Shoudn't crash

**Environment (remove any that are not applicable):**
 - Giltab runner version : 12.1.0

**Additional context**
Here's the whole log
```
Running with gitlab-runner 12.1.0 (de7731dd)
  on Autoscalling runner 8a6fef31
Using Docker executor with image stoplight/spectral ...
Pulling docker image stoplight/spectral ...
Using docker image sha256:1138f1564cd3ae6b28b639d00b4ecde1f7c1013436f76fd8622b07c5892790a2 for stoplight/spectral ...
Running on runner-8a6fef31-project-661-concurrent-0 via runner-8a6fef31-gitlab-docker-machine-1590659054-9111b302...
Fetching changes with git depth set to 50...
Initialized empty Git repository in [REDACTED]
Created fresh repository.
From [REDACTED]
 * [new ref]         refs/pipelines/9489 -> refs/pipelines/9489
 * [new branch]      develop             -> origin/develop
Checking out 8d691582 as develop...

Skipping Git submodules setup
spectral <command>

Commands:
  spectral lint [documents..]  lint JSON/YAML documents from files or URLs

Options:
  --version  Show version number  [boolean]
  --help     Show help  [boolean]

Unknown arguments: c, sh
ERROR: Job failed: exit code 1
````

**Comment by vincent-paing** [comment]
I used [spectral image from kiwicom ](https://github.com/kiwicom/dockerfiles )instead and it works

**Comment by nulltoken** [comment]
@vincent-paing 

Just checking. what happens if you change your config to the following?

```
stages:
  - lint

lint:
  stage: lint
  image: stoplight/spectral
  script:
    - lint ./*.yaml
```

**Comment by vincent-paing** [comment]
@nulltoken Same error as above

```
Checking out 4531e635 as develop...

Skipping Git submodules setup
spectral <command>

Commands:
  spectral lint [documents..]  lint JSON/YAML documents from files or URLs

Options:
  --version  Show version number  [boolean]
  --help     Show help  [boolean]

Unknown arguments: c, sh
spectral <command>

Commands:
  spectral lint [documents..]  lint JSON/YAML documents from files or URLs

Options:
  --version  Show version number  [boolean]
  --help     Show help  [boolean]

Unknown arguments: c, sh
ERROR: Job failed: exit code 1
```

**Comment by nulltoken** [comment]
@vincent-paing the `Unknown arguments: c, sh` looks a bit weird. Especially when you find part of them in the GitLab [doco](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image) about "Overriding the entrypoint".

I'm wondering if what you're actually facing is actually more related to GitLab infra rather than Spectral itself

Googling for "https://www.google.com/search?q=gitlab+docker+entrypoint+c+sh" also returns results.

It's possible the GitLab default runner configuration doesn't play well with Spectral Alpine based dockerfile (which defines an ENTRYPOINT of its own).

Few thoughts:
- Is there a way to configure GitLab so that it runs in verbose mode?
- https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-image seems to show that the entrypoint can be overridden.
- This might also be relevant

![image](https://user-images.githubusercontent.com/92363/83391962-98da1c00-a3f4-11ea-99af-ffacb3419b61.png)

**Comment by nulltoken** [comment]
@vincent-paing Maybe should you also consider asking "How can I leverage the Spectral docker image from GitLab" at https://community.stoplight.io/ and report back here with your findings? 

Would GitLab require specific setup, that would be a great addition to the documentation.

**Comment by nulltoken** [comment]
>Would GitLab require specific setup, that would be a great addition to the documentation.

@vincent-paing Have you managed to troubleshoot the issue?

**Comment by vincent-paing** [comment]
Not yet. I'm just using the image I mentioned above now.

**Comment by hpatoio** [comment]
I stumbled into this issue too. After reading here https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692#note_50147081 I was able to successfully use the official image with this yml

```yml
stages:
  - validate

validate_open-api:
  stage: validate
  image:
    name: stoplight/spectral
    entrypoint: [""]
  script:
   - spectral lint open-api.json
```

**Comment by nulltoken** [comment]
@hpatoio Awesome!

Would you feel like sharing this more widely and open a PR to update `/docs/getting-started/2-installation.md`?
