### ISSUE TITLE
No Docker image tagged for 5.7.x, 5.8.x

### ISSUE THREAD

**Issue by fgabolde** [stoplightio/spectral#1479]
Although there are Docker images tagged with 5.4, 5.5, 5.6, there are none for the later releases.

There is an image tagged `5` but it is unclear what version that would be. This is problematic for a CI environment, which relies on stable images that don't change automatically.

**Comment by fgabolde** [comment]
Update two months later:

* there is a `develop` tag, pushed 5 months ago -- I don't know what build this is, maybe 5.7.0?
* there is a `5` tag, 4 months ago -- 5.7.2?
* there is a `latest` tag that seems to point to the same image as `5`
* there is a `master` tag which probably contains the 5.9.0 release

I'm guessing at the release numbers here based on the dates but I don't really know what version I'm pulling for sure. I have resorted to pinning the current SHA that `master` is pointing to since I can't assume that the tag will be immutable.

Initially I wanted to upgrade to 5.8.x, but I can't find any Docker tag pointing to it so have upgraded to 5.9.0 instead.

See also the related issue https://github.com/stoplightio/spectral/issues/1483 which only exacerbates this issue.

**Comment by philsturgeon** [comment]
Can we get rid of the master tag? That's probably not a useful thing and we should be changing to main in git at some point anyway.

**Comment by wmhilton** [comment]
yeah.. we're having weird problems with "git clone" not working in Docker Hub. If I can't figure out a way around it, we'll have to move the build pipeline to Circle CI.

We're running into a problem very similar to this open issue: https://github.com/docker/hub-feedback/issues/1777

**Comment by wmhilton** [comment]
Oh @philsturgeon um. We can remove the `master` tag but it'll screw up somebody's workflow. It was last pulled an hour ago:

![image.png](https://images.zenhubusercontent.com/5d3f1460cc4b911f8f2fadff/4a9b9f10-87af-4ea0-9c04-8684797a6c28)

**Comment by wmhilton** [comment]
Aaaand does not correspond to any other existing tagged image. Also, `5` and `5.6` don't point to the same image which disturbs me. :D

![image.png](https://images.zenhubusercontent.com/5d3f1460cc4b911f8f2fadff/6dd5f20c-5db9-4da7-9cdf-4eca1715846a)

**Comment by wmhilton** [comment]
I think what I'll do is manually build and push images for 5.9.1, and then we can make an issue to upgrade the CI pipeline for the 6.x series to not rely on DockerHub's build service.

**Comment by philsturgeon** [comment]
> We can remove the master tag but it'll screw up somebody's workflow. It was last pulled an hour ago:

They should not be on master anyway, we have breaking changes coming and that will also cause broken stuff. I think its ok if we pick a new strategy which is common in docker land, and reliably updated, and if one person gets a broken workflow they'll come and see our excellent new tags and pick the one they like the most. 

They might only on master because its the only way to get newer versions. They will probably be ok picking a stable major version tag.

**Comment by wmhilton** [comment]
@philsturgeon done! no more master

I succeeded in manually building and tagging `5.9.1` and `5.9` on my machine. I'll manually update `latest` to point to that image as well.

**Comment by aleskovets** [comment]
Just tried `5.9.1` in our pipeline. Works as a charm. Thanks

**Comment by wmhilton** [comment]
Oh lovely!

I think, since 5.8 and 5.7 aren't really supported, there's not much point in making docker tags for them. So I shall close this unless someone specifically wants docker tags for 5.8 and 5.7.

I'm working on improving the automatic docker tagging for the 6.x series, it should be much better.

**Comment by philsturgeon** [comment]
Brilliant will, thank you!
