### ISSUE TITLE
Releasing merged features?

### ISSUE THREAD

**Issue by exoszajzbuk** [stoplightio/spectral#1507]
**Chore summary**
There are several new features/fixes on the `develop` branch which didn't get into 5.8.1 which was released in the meantime. For example these commints:
* https://github.com/stoplightio/spectral/commit/0a8e0a6cbd53018d84352f749ba6ee2b71320498
* https://github.com/stoplightio/spectral/commit/3a5905583ae09f904c66c807e6f175cb9ce6ab04
* https://github.com/stoplightio/spectral/commit/e8c1846c5ea81402d7e79bd4f9e741b95eb46bfb

**Tasks**
- [ ] Create new release with previously unreleased features

**Comment by P0lip** [comment]
Hey, we'll certainly make a release soon, and both 0a8e0a6 and e8c1846c5ea81402d7e79bd4f9e741b95eb46bfb will be a part of it.
3a59055, however, is scheduled for 6.0.

**Comment by mkistler** [comment]
@P0lip I think 3a59055 can be reworked to be backward compatible, and I am willing to do that if you will put that into the next release.

We are also waiting on baf3883.  Is that scheduled for the next release?

**Comment by P0lip** [comment]
> We are also waiting on baf3883. Is that scheduled for the next release?

@mkistler Hey! baf3883 is to be included in the next release.
If time allows, 5.9 will be out this week.

> @P0lip I think 3a59055 can be reworked to be backward compatible, and I am willing to do that if you will put that into the next release.

3a59055, however, is scheduled for the next major release, and therefore is not planned to be a part of the next version.
Would a custom ruleset be a solution for you until we get the major version out?

Side note - one of the changes I'd love to get done soon is converting Spectral to monorepo. Independent versioning is becoming increasingly important due to a number of issues related to purely to rulesets. In such a setup, rulesets would have their own release cycle. This would eventually lead to faster iterations, as a ruleset breaking change wouldn't imply a CLI / core breaking change, if you know what I mean.

**Comment by mkistler** [comment]
@P0lip regarding 3a59055, we already have a custom rule. We are trying to eliminate our custom rules that duplicate Spectral rules.

If the release after 5.9 is going to be a major version, then I guess we can just wait.  But if there is going to be a 5.10, then I would like to submit a PR that makes the change in 3a59055 in a backward compatible way so that it can be included.

**Comment by P0lip** [comment]
> If the release after 5.9 is going to be a major version, then I guess we can just wait. But if there is going to be a 5.10, then I would like to submit a PR that makes the change in 3a59055 in a backward compatible way so that it can be included.

I'm hoping to get a major soon.
Maintaining v5 is increasingly becoming challenging, because the codebases have diverged notably, and cherry-picking certain changes is not straighforward.
If 6.0 does not happen soon, I'll rewrite the rule for you and get it out in 5.10.
