### ISSUE TITLE
Fix security vulnerability (lodash)

### ISSUE THREAD

**Issue by damianobarbati** [stoplightio/spectral#1617]
**Chore summary**
``` bash
yarn add @stoplight/spectral
yarn audit
```
<img width="988" alt="Screenshot 2021-05-12 at 09 13 19" src="https://user-images.githubusercontent.com/2225869/117933850-4d1d3b80-b302-11eb-833b-49d8385542a5.png">

**Tasks**
Bump lodash version >= 4.17.21

**Comment by tsimbalar** [comment]
Would it make sense for the project to not use an exact version of dependencies, and instead use a version range ?

This would allow to address security vulnerabilities without needing to release new versions of `spectral` 🤔 

i.e. by updating the `package.json` and instead of `"lodash": "4.17.21",` , using things like 

`"lodash": "^4.17.21",` ->  any `4.x` 

or

`"lodash": "~4.17.21",` ->  any `4.17.x`

**Comment by jrhorn424** [comment]
I'm probably stating the obvious, but tilde is safer. That's what I've used for production applications when pinning exact versions isn't required.

**Comment by kilahm** [comment]
Looks like #1585 solves this?

**Comment by hiddewie** [comment]
Could #1585 be released in a 5.x patch version? Thanks in advance!

**Comment by P0lip** [comment]
Fixed in 5.9.2!
