### ISSUE TITLE
New releases due to security vulnerabilities

### ISSUE THREAD

**Issue by Linuus** [stoplightio/spectral#1969]
**Chore summary**

Make a new release to bump jsonpointer library as it has security vulnerabilities. It is a dependency on better-ajv-errors and it looks like it has already been bumped in core. I believe you need a new core release and then bump the dependency in cli?

**Tasks**
- [ ] New release of core
- [ ] Bump core version in cli and release

**Comment by P0lip** [comment]
Core has been released. :tada:
There's no need to bump it in CLI yet, you should be able to bump the version of core.

**Comment by Linuus** [comment]
> Core has been released. 🎉 There's no need to bump it in CLI yet, you should be able to bump the version of core.

@P0lip Are you sure? I mean... CLI still have a dependency on an old core version so if it's not changed it will still pull the old better-ajv-errors and get a vulnerable dependency.

Dependabot still gives me this:
> @stoplight/spectral-cli@6.1.0 requires jsonpointer@^4.0.1 via a transitive dependency on @stoplight/better-ajv-errors@0.2.0

even if I have this:
```
    "@stoplight/spectral-core": "^1.7.0",
    "@stoplight/spectral-cli": "^6.1.0",
```

So, maybe we do need to bump the versions in CLI after all?

**Comment by dpopp07** [comment]
@P0lip The latest release of `@stoplight/spectral-rulesets` still depends on an old version of `@stoplight/better-ajv-errors` ("0.2.0"). When will a new release of the rulesets package go out? I see the `better-ajv-errors` dependency is fixed in the package.json on GitHub but when I install it I get the old version.

**Comment by P0lip** [comment]
> @P0lip Are you sure? I mean... CLI still have a dependency on an old core version so if it's not changed it will still pull the old better-ajv-errors and get a vulnerable dependency.

It's not a fixed dependency though meaning that as soon as your npm/yarn cache is busted, a newer one will be picked up.

> The latest release of @stoplight/spectral-rulesets still depends on an old version of @stoplight/better-ajv-errors ("0.2.0"). When will a new release of the rulesets package go out? 

When we have some changes worth publishing. I don't know when exactly, but it may take a while.
As mentioned before in some different ticket, our code doesn't use the vulnerable parts of the code, so you can rest assured you're not at risk.

**Comment by dpopp07** [comment]
> As mentioned before in some different ticket, our code doesn't use the vulnerable parts of the code, so you can rest assured you're not at risk.

I hadn't seen that, thanks.

**Comment by P0lip** [comment]
Yeah, generally if there was a risk we'd update everything immediately, but in this particular case, we're safe.
Either way, I'm aware that it's still possibly annoying since our package is presumably flagged by some tools, therefore I'll try to get a new release out when I have a chance.
I have some CLI changes coming up in my pipeline, so a new version of CLI should be published as well.
