### ISSUE TITLE
How to use spectral using .tar file

### ISSUE THREAD

**Issue by JGPrakash** [stoplightio/spectral#2155]
I download the .tar file using the link - https://github.com/stoplightio/spectral/releases
how to access it? (As per my company policy we are not allowed to use NPM and exe installation)

**Comment by P0lip** [comment]
The .tar file is basically a snapshot of the repo at a given point at the time.
It's just a source code you'd need to compile in order to use it.
The installation instructions are here https://github.com/stoplightio/spectral/blob/develop/CONTRIBUTING.md#development, but one would still need to use `npm`.

FWIW, the distributed binaries do not need to be installed. You just download it and run using CLI.
