### ISSUE TITLE
Resource name must be plural and noun

### ISSUE THREAD

**Issue by AshwithGundu** [stoplightio/spectral#295]
Is there any existing rule OOTB to check whether the resource name in noun, plural.

Ex: Noun: Must be 'employee' instead of 'getEmployees'
     Plural: Must be 'games' not 'game'

It would be good if anyone can give me the regex pattern for the above mentioned rules.

Regards,
Ashwith

**Comment by philsturgeon** [comment]
Hey there! We've just started a big documentation push there is a ways to go. Writing custom functions is not something we've got covered, but take a look in the docs/ folder to see if anything helps.

You probably won't get very far with regex, because `bus` is singular and `sheep` is plural. Check out existing tools like: https://www.npmjs.com/package/pluralize

If you can make a custom function which wraps this, you're off to a good start.

**Comment by philsturgeon** [comment]
Ok so custom functions in rulesets is #311 but maybe we can consider getting some pluralize logic in the core as its commonly required functionality.

**Comment by philsturgeon** [comment]
This will need to be taken care of with custom function for now.

**Comment by Nicoolai** [comment]
> If you can make a custom function which wraps this, you're off to a good start.

How would you go about doing this?
Can we use npm packages in custom functions? 
Or is it a matter of adding the code, from that library, into the custom function code?
