### ISSUE TITLE
Load Rulesets via JS API 

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#366]
**User story.**
As a developer working with the JS API, I can do reference a custom ruleset (path, url, required from a NPM module), so that I do not need to mess around with the addRules() and addFunctions() interface. 

_This ticket should deprecate those two methods, but is not responsible for adding custom functions to rulesets. That will be handled in_ https://github.com/stoplightio/spectral/issues/311

**Is your feature request related to a problem?**
V4.0 made it way easier to work with custom rulesets but working with the TS/JS interface still feels pretty clunky. 

**Describe the solution you'd like**

TBD on the exact interface. 
```
spectral.loadRuleset(‘file://something’)
```

**Additional context**

Relates to #365

**Comment by marbemac** [comment]
Generally feels good - what about expecting end user to load/read the file themselves? So would look more like this:

```
spectral.setRuleset(ruleset: IRuleset)
```

Where IRuleset is https://github.com/stoplightio/spectral/blob/develop/src/types/ruleset.ts#L17.

I guess we could also have `loadRuleset` that takes a file or url, fetches it, and calls `setRuleset` with the result.

OR since ruleset extends supports files and urls, might be able to get away with something as simple as this for `loadRuleset`?

```ts
function loadRuleset(rulesetLocation: string) {
  spectral.setRuleset({
      extends: rulesetLocation,
  });
}
```

Kinda snazzy if that just works :).

**Comment by P0lip** [comment]
@marbemac 
I believe we should support both - a plain ruleset path/name and a parsed ruleset.
This is kind of similar to what we do with spec - you can provide a parsed spec, but also a string if you'd like to.

The problem with the ruleset approach only is that API consumer would need to call `resolveRuleset` function on its own if shorthands or npm modules are meant to be resolved.
Not to mention potential issues in browser environment if `fs` module is used.

**Comment by P0lip** [comment]
Another potential issue with `spectral.setRuleset(ruleset: IRuleset)`.
A consumer would also need to resolve extended rulesets on its own.
We could resolve them, but relative paths to rulesets would be *very* tricky to support... I'd say almost impossible since we don't know the base path of parent ruleset and would need to speculate a lot and make lots of assumptions that will never work under all circumstances.

**Comment by marbemac** [comment]
> A consumer would also need to resolve extended rulesets on its own.

Slightly confused - I guess you're suggesting this would be handled in `loadRuleset`? If we can get it done in a `loadRuleset` function, why would we not be able to do it in another function?

**Comment by P0lip** [comment]
> Slightly confused - I guess you're suggesting this would be handled in loadRuleset? If we can get it done in a loadRuleset function, why would we not be able to do it in another function?

@marbemac, Sorry for dropping a ball on this one.
What I'm saying is that loading the following ruleset might be a serious trouble
```yaml
extends: ['./foo.yaml']
rules:
  # some rules
```
How do you resolve `./foo.yaml` path when you don't know the base path?
Does the following example make the situation more clear?

**Comment by philsturgeon** [comment]
@marbemac @P0lip hey, it seems like you two were discussing some cool ideas for how the `loadRuleset()` this ticket suggests could be a helper for a `setRuleset()`, but there seemed to also be concerns with the actual code being suggested. 

It's getting close to implementation time, and I'd like to make sure this ticket has an implementation that somebody can pick up. Can we punt the setRuleset ideas for now and expose it as a new method later on? 

I think we can get away with a simple `loadRulesets()` function which is doing what `loadRules()` and `loadFunctions()` are currently doing? Seem ok?

**Comment by P0lip** [comment]
> Can we punt the setRuleset ideas for now and expose it as a new method later on?

Yeah, I'd vote for holding on with that idea for a while and sticking to the original idea (`loadRuleset` method only).

I'd like to work on that one, so lack of some details shouldn't be an issue. :D
Before we start that one, though, we need to have custom functions in place.
