### ISSUE TITLE
Support breaking changes detection

### ISSUE THREAD

**Issue by RomainSimiand** [stoplightio/spectral#483]
**User story.**
As an API designer, I can check if my new API specification is introducing breaking changes, so that I can warn my API consumers or make changes to avoid these changes.

**Is your feature request related to a problem?**
Linting my API specs against both generic OAI2/3 and my company's guidelines is amazing, but I wish I could also be warned by spectral when my API specs are introducing breaking changes. This is inheritent of most API guidelines I'm aware of and would definitely become handy.

**Describe the solution you'd like**
The best way would be to allow spectral to compare my current specs with the previous main one.

**Additional context**
I understand this could introduce some complexity in spectral itself,and that various tools already exist for that purpose, but regarding the OAI ecosystem, I strongly feel tools like spectral should cover this use case. It's active, is flexible, and imho should become the one stop tool for API designers.

Hope this makes sense, and dosen't sound too much of a stretch regarding spectral's original purpose.

Thanks!

**Comment by philsturgeon** [comment]
This is actually something we are covering in the larger [Stoplight.io](http://stoplight.io) platform. It's going to get more powerful over time, but we already detect breaking changes and bump the versions of a model when it changes, but the interface for this has not surfaced just yet. Gotta polish a few more things.

We do this at that level, because we need our analyzer to run over time to detect changes. This extra dimension of time means we have the ability to diff, which we cannot do from just looking at an openapi.yaml once right now. 

The future functionality will have all sorts of "warning this is a breaking change" and "email subscribers of your API" so it really feels like the right place to solve it. 

I'll leave this open for a little bit to see if there are any ideas from the community here, but I think we're already on the right path, keeping Spectral unaware of time.

**Comment by RomainSimiand** [comment]
Cheers @philsturgeon,

totally understood, can't wait to see this bubble up in stoplight.io :)

**Comment by dusan-dragon** [comment]
Hi @philsturgeon I think it would be nice to have this feature in cli also, so we can apply it to git diff (by providing actual version and master version of contract)

**Comment by philsturgeon** [comment]
@dusan-dragon it's not something that Spectral will ever do, because Spectral only understands the current document. It does not have a concept of time, versions, changes, breakages, only what currently is. There is more room in the world for more [OpenAPI tools](https://openapi.tools) if this is not covered too well by existing tools like openapi-diff, but Spectral isn't that tool. 

A vote for the [automatic changelog](https://roadmap.stoplight.io/c/29-automatic-changelogs) feature for Stoplight would get us building out more logic that helps with sensing changes and breaks, so if we noticed the tools are no good we'll either make them better or release our own! :)
